---
- name: Test network share access
  hosts: windows_10
  gather_facts: false

  tasks:
    - name: Show current user
      raw: whoami

    - name: Test share access
      raw: powershell.exe -Command "Test-Path '\\10.64.105.105\mostafa\Bangla\setup_avrokeyboard_5.6.0.exe'"

    - name: List share contents
      raw: powershell.exe -Command "Get-ChildItem '\\10.64.105.105\mostafa\Bangla'"
