---
- name: Copy Avro Keyboard installer from Windows share
  hosts: windows_10
  gather_facts: false

  tasks:
    - name: Copy file with Robocopy
      ansible.windows.win_command: >
        robocopy "\\10.64.105.105\mostafa\Bangla"
        "C:\Temp"
        "setup_avrokeyboard_5.6.0.exe"
        /R:3 /W:5
      register: robocopy

    - name: Fail if Robocopy failed
      ansible.builtin.fail:
        msg: "Robocopy failed with exit code {{ robocopy.rc }}"
      when: robocopy.rc > 7
