---
- name: Create file on Windows
  hosts: windows
  gather_facts: no

  tasks:
    - name: Create Semaphore.txt
      ansible.windows.win_copy:
        dest: C:\Semaphore.txt
        content: |
          This file was created by Ansible.
          Welcome to Semaphore.
          Windows WinRM test successful.
