---
- name: Create a folder on Windows
  hosts: windows
  gather_facts: false

  tasks:
    - name: Create C:\temp\MyFolder
      ansible.windows.win_file:
        path: C:\temp\MyFolder
        state: directory
