---
- name: Create a text file on Windows
  hosts: 10.64.105.52
  gather_facts: false

  tasks:
    - name: Create test.txt
      raw: echo Hello from Ansible> C:\temp\test.txt
      register: result

    - name: Show result
      debug:
        var: result
